name: main-pipeline

on:
  push:
    branches: [main]

env:
  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
  GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
  GRADLE_API_KEY: ${{ secrets.GRADLE_API_KEY }}
  GRADLE_API_SECRET: ${{ secrets.GRADLE_API_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - run: |
          ./gradlew build