name: release-pipeline

on:
  release:
    types: [published]

env:
  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
  GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
  GRADLE_API_KEY: ${{ secrets.GRADLE_API_KEY }}
  GRADLE_API_SECRET: ${{ secrets.GRADLE_API_SECRET }}

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish
        uses: gradle/gradle-build-action@v2
      - run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -PbuildVersion=${NEW_VERSION} -Pgradle.publish.key=${GRADLE_API_KEY} -Pgradle.publish.secret=${GRADLE_API_SECRET} build publishPlugins --info